module.exports = {
  WHATSAPP_MESSAGE_RECEIVED: "WHATSAPP_MESSAGE_RECEIVED",
  AI_RESPONSE_GENERATED: "AI_RESPONSE_GENERATED",
  MESSAGE_DELIVERED: "MESSAGE_DELIVERED",
  ERROR_OCCURRED: "ERROR_OCCURRED"
};
