const AfriAIExecutionStatus = {
  CREATED:"CREATED",
  PREVIEW:"PREVIEW",
  AWAITING_APPROVAL:"AWAITING_APPROVAL",
  APPROVED:"APPROVED",
  EXECUTING:"EXECUTING",
  COMPLETED:"COMPLETED",
  FAILED:"FAILED",
  CANCELLED:"CANCELLED",
  EXPIRED:"EXPIRED"
};

export default AfriAIExecutionStatus;
