const AfriPlatformRolePermissions = {
  SUPER_ADMIN:["*"],
  PLATFORM_ADMIN:["PLATFORM_MANAGE","USERS_MANAGE","VERIFICATION_MANAGE","TRUST_MANAGE","MEMBERSHIP_MANAGE","CONTENT_MODERATE","ANALYTICS_VIEW"],
  PRODUCT_ADMIN:["PRODUCT_CREATE","PRODUCT_UPDATE","PRODUCT_DELETE","ORDER_MANAGE","ANALYTICS_VIEW"],
  MODERATOR:["CONTENT_MODERATE","SUPPORT_MANAGE"],
  SELLER:["LISTING_CREATE","LISTING_UPDATE","LISTING_DELETE","PROFILE_UPDATE"],
  USER:["PROFILE_UPDATE"]
};

export default AfriPlatformRolePermissions;
