const AfriPlatformPermissions = [
  "PLATFORM_MANAGE",
  "USERS_MANAGE",
  "VERIFICATION_MANAGE",
  "TRUST_MANAGE",
  "MEMBERSHIP_MANAGE",
  "PRODUCT_CREATE",
  "PRODUCT_UPDATE",
  "PRODUCT_DELETE",
  "ORDER_MANAGE",
  "PAYMENT_MANAGE",
  "CONTENT_MODERATE",
  "SUPPORT_MANAGE",
  "ANALYTICS_VIEW",
  "PROFILE_UPDATE",
  "LISTING_CREATE",
  "LISTING_UPDATE",
  "LISTING_DELETE"
];

export default AfriPlatformPermissions;
