module.exports = {
  WHATSAPP_MESSAGE: "WHATSAPP_MESSAGE",
  JOB_CREATED: "JOB_CREATED",
  JOB_COMPLETED: "JOB_COMPLETED",
  AD_POSTED: "AD_POSTED",
  WALLET_TOPUP: "WALLET_TOPUP",
  WITHDRAWAL_REQUESTED: "WITHDRAWAL_REQUESTED",
  AI_RESPONSE: "AI_RESPONSE",
  FRAUD_FLAG: "FRAUD_FLAG",
  USER_REGISTERED: "USER_REGISTERED"
};
