export const AFRI_CRYPTO_TRANSACTION_TYPES = Object.freeze({
  TRANSFER: "TRANSFER",
  RECEIVE: "RECEIVE",
  SEND: "SEND",
  MINT: "MINT",
  BURN: "BURN"
});

export const AFRI_CRYPTO_TRANSACTION_STATUS = Object.freeze({
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  CONFIRMED: "CONFIRMED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED"
});
