module.exports = {
  WHATSAPP_MESSAGE: "MESSAGE_RECEIVED",
  AI_RESPONSE: "RESPONSE_GENERATED",
  JOB_POSTED: "JOB_POSTED",
  JOB_APPLIED: "JOB_APPLIED",
  AD_POSTED: "AD_POSTED",
  WALLET_TOPUP: "WALLET_TOPUP",
  WALLET_WITHDRAW: "WALLET_WITHDRAW",
  PAYSTACK_SYNC: "PAYSTACK_SYNC",
  TRAINING_CYCLE: "AI_TRAINING_CYCLE"
};
