const AfriDebugHTMLEvidenceExporter={

  export(evidence={}){

    const html=`<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>AfriDebug Evidence Report</title>
<style>
body{font-family:Arial,sans-serif;margin:40px;background:#f5f5f5;}
.card{background:#fff;padding:24px;border-radius:8px;border:1px solid #ddd;}
h1{color:#0f766e;}
table{width:100%;border-collapse:collapse;margin-top:20px;}
td{border:1px solid #ddd;padding:8px;}
td:first-child{font-weight:bold;width:220px;}
.footer{margin-top:20px;font-size:12px;color:#666;}
</style>
</head>
<body>
<div class="card">
<h1>AfriDebug Evidence Report</h1>
<table>
<tr><td>Evidence ID</td><td>${evidence.evidenceId||""}</td></tr>
<tr><td>Incident</td><td>${evidence.incidentId||""}</td></tr>
<tr><td>Connector</td><td>${evidence.connector||""}</td></tr>
<tr><td>Repository</td><td>${evidence.repository||""}</td></tr>
<tr><td>Component</td><td>${evidence.component||""}</td></tr>
<tr><td>Issue</td><td>${evidence.issue||""}</td></tr>
<tr><td>Severity</td><td>${evidence.severity||""}</td></tr>
<tr><td>Risk</td><td>${evidence.risk||""}</td></tr>
<tr><td>Integrity Hash</td><td>${evidence.integrityHash||""}</td></tr>
</table>
<div class="footer">
Generated by AfriDebug Evidence Exporter
</div>
</div>
</body>
</html>`;

    return{
      exportId:"HTML-"+Date.now(),
      format:"html",
      fileName:`${evidence.evidenceId||"evidence"}.html`,
      content:html,
      exportedAt:Date.now()
    };

  },

  health(){

    return{
      service:"AfriDebugHTMLEvidenceExporter",
      status:"healthy"
    };

  }

};

export default AfriDebugHTMLEvidenceExporter;
