const e = process.env;

console.log("🧠 RENDER ENVIRONMENT REALITY CHECK");
console.log({
  REDIS: !!e.REDIS_URL,
  META_ACCESS_TOKEN: !!e.META_ACCESS_TOKEN,
  META_PHONE_NUMBER_ID: !!e.META_PHONE_NUMBER_ID,
  META_VERIFY_TOKEN: !!e.META_VERIFY_TOKEN,
  WHATSAPP_TOKEN: !!e.WHATSAPP_TOKEN,
  WHATSAPP_PHONE_ID: !!e.WHATSAPP_PHONE_ID,
  NODE_ENV: e.NODE_ENV,
  KEYS_COUNT: Object.keys(e).length
});
