module.exports = {
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  RESPONSE_GENERATED: "RESPONSE_GENERATED",

  SERVICE_HEALTH_OK: "SERVICE_HEALTH_OK",
  SERVICE_HEALTH_FAIL: "SERVICE_HEALTH_FAIL",

  THOUGHT_GENERATED: "THOUGHT_GENERATED",
  MEMORY_WRITTEN: "MEMORY_WRITTEN",

  PAYSTACK_PAYMENT_SUCCESS: "PAYSTACK_PAYMENT_SUCCESS",
  PAYSTACK_PAYMENT_FAILED: "PAYSTACK_PAYMENT_FAILED",

  RENDER_HEALTH_OK: "RENDER_HEALTH_OK",
  RENDER_HEALTH_FAIL: "RENDER_HEALTH_FAIL"
};
